version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongovolume:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  api:
    image: node:14-alpine
    tty: true
    volumes:
      - ./Api:/app
      - nodemodules:/usr/src/app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - CHOKIDAR_USEPOLLING=true

  app:
    image: node:14-alpine
    tty: true
    volumes:
      - ./app:/app:cached
      - reactmodules:/usr/src/app/node_modules
    working_dir: /app
    command: npm start
    depends_on:
      - api
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  nodemodules: {}
  reactmodules: {}
  mongovolume: {}
